name: covid19

services:
    app:
        image: covid19
        container_name: covid19
        build:
            context: .
            dockerfile: Containerfile
        ports:
            - 3000:5173
        volumes:
            - .:/app:z
